### ISSUE TITLE
Library Will Not Compile in Production

### ISSUE THREAD

**Issue by MattyK14** [dbolcsfoldi/react-native-external-accessory#2]
Project builds fine as `debug`, but trying to `archive` or changing the scheme to `release` produces the following: 
```
ld: library not found for -lEAMExternalAccessory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dbolcsfoldi** [comment]
Hi Matt,

thanks for raising this. The issue should now be fixed - I had to regenerate the xcode project to resolve it. Please try it out and see if it works for you as well.

Thanks,
David
