### ISSUE TITLE
hasListener is always false

### ISSUE THREAD

**Issue by vikaschandra** [dbolcsfoldi/react-native-external-accessory#4]
We should call startObserving in startSearch so that hasListner becomes true and it sends the events back to jsLayer. Currently it never sends any event.

**Comment by dbolcsfoldi** [comment]
Hi Vikas,

startObserving is called by the RCTEventEmitter parent class when addEventListener is called. Or should be anyway according to RCTEventEmitter docs :-)

If this is not what you are seeing could you elaborate?

Thanks,
David

**Comment by dbolcsfoldi** [comment]
OK I will go ahead and close this issue. If you see this issue crop up again, please feel free to raise the issue again.
