### ISSUE TITLE
Support for iOS 10

### ISSUE THREAD

**Issue by vikaschandra** [dbolcsfoldi/react-native-external-accessory#5]
Currently it has deployment target as 11.1. Please enable for iOS 10.

**Comment by dbolcsfoldi** [comment]
The repository xcode project has deployment target as 8.0 - are you working off a local branch perhaps?

**Comment by vikaschandra** [comment]
I see your code has changes but npm does not have. npm still shows the publish date as 1 year ago.Please publish a new version.

**Comment by dbolcsfoldi** [comment]
Can do for sure, is the issue resolved for you then?
