### ISSUE TITLE
[RCTUIManager UIManager] always returns nil

### ISSUE THREAD

**Issue by vikaschandra** [dbolcsfoldi/react-native-external-accessory#6]
In configure method to present the UI, 
UIView *responder = [RCTUIManager JSResponder]; always returns nil so controller is also nil, in my project.
but if I use [UIApplication sharedApplication].delegate.window.rootViewController;
to get controller it works.
I am using react-navigation for UI navigation.
Can you please handle and update the repository?

**Comment by dbolcsfoldi** [comment]
Hi Vikas,

maybe I am not fully understanding but could you please explain how the issue above relates to react-native-external-accessory?

Thanks!

**Comment by vikaschandra** [comment]
This is related because without this change in configure call, the Airport setup screen won't be presented and wifi cannot be configured.

**Comment by dbolcsfoldi** [comment]
I see - I never tried it with react-navigation. I've pushed a change to grab the root view controller if the first responder is missing.
